apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: auth
    spec:
      containers:
      - env:
        - name: DB_PASS
          value: pass
        - name: DB_USER
          value: authdb
        - name: JDBC_URL
          value: jdbc:postgresql://auth-db:5432/authdb
        image: brunoribca/auth:1.0-SNAPSHOT
        imagePullPolicy: "Always"
        name: auth
        ports:
        - containerPort: 4567
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
