apiVersion: v1
data:
  0_init.sql: |-
    -- 256 bitlen hash -> 64 chars hexa string
    CREATE TABLE USERS(
    ID INT PRIMARY KEY NOT NULL,
    USERNAME VARCHAR(32) NOT NULL UNIQUE,
    PASSWORD CHAR(64) NOT NULL,
    SALT CHAR(16) NOT NULL,
    EMAIL VARCHAR(64) NOT NULL UNIQUE
    );
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-03T11:10:15Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:0_init.sql: {}
    manager: kubectl
    operation: Update
    time: "2020-05-03T11:10:15Z"
  name: auth-init-db
  namespace: default
  resourceVersion: "889494"
  selfLink: /api/v1/namespaces/default/configmaps/auth-init-db
  uid: 941f013d-155b-4523-88c6-b6693e0d23bf
