apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: workflow-db
  name: workflow-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: workflow-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: workflow-db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: workflow
        - name: POSTGRES_PASSWORD
          value: pass
        - name: POSTGRES_USER
          value: workflow
        image: postgres:9.6-alpine
        imagePullPolicy: "Always"
        livenessProbe:
          exec:
            command:
            - pg_isready -U workflow
          failureThreshold: 5
          periodSeconds: 10
          timeoutSeconds: 5
        name: workflow-db
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: workflow-db-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: workflow-db-claim0
        persistentVolumeClaim:
          claimName: workflow-db-claim0
status: {}
