apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: auth
  name: auth
spec:
  ports:
  - name: "4567"
    port: 4567
    targetPort: 4567
  selector:
    io.kompose.service: auth
status:
  loadBalancer: {}
